### ISSUE TITLE
Error in checkboxtreeview.py line # 175

### ISSUE THREAD

**Issue by WinEunuuchs2Unix** [TkinterEP/ttkwidgets#66]
This is really trivial but I thought I would share my first few minutes of experience converting an existing ttk.Treeview() to CheckboxTreeview().

First this error at line 175:

```
kw["tags"] += (tag,)
TypeError: cannot concatenate 'str' and 'tuple' objects

```
My tree already contained tags for grandparent = "Artist", parent = "Album" and child = "Song".

So I changed the code thusly:

```
# TypeError: cannot concatenate 'str' and 'tuple' objects
try:                                # Oct 24 2020 fix exception
    kw["tags"] += (tag,)
except TypeError:                
     kw["tags"] += tag

```

The error went away but the treeview had NO checkboxes!

So I changed my existing tags and appended "unchecked" to all of them:
```

tags=("Artist", "unchecked"), open=True, \
text=Album, tags=("Album", "unchecked"), \
tags=("Song", "unchecked"), values = (ftime, fsize, '', \

```

Voila! checkboxes appeared and I can reverse changes to checkboxtreeview.py with:

`sudo apt-get install --reinstall python-ttkwidgets`

I hope this helps others. CheckboxTreeview() is an awesome extension to ttk.Treeview()!

**Comment by RedFantom** [comment]
Thank you for opening this issue!

As far as I understand it, the code is not at fault, exactly, but there may be some unclarity. The only way I could find to reproduce your issue is to insert an item in the following manner, modified from `example_checkboxtreeview.py`:
```python
tree = CheckboxTreeview(root)
tree.pack()

tree.insert("", "end", "1", text="1", tags=("hello","world"))
tree.insert("1", "end", "11", text="11", tags=("hello"))
```
This produces the error on Python 3.8:
```python
Traceback (most recent call last):
  File "/home/user/Source/ttkwidgets/examples/example_checkboxtreeview.py", line 15, in <module>
    tree.insert("1", "end", "11", text="11", tags="hello")
  File "/home/user/Source/ttkwidgets/ttkwidgets/checkboxtreeview.py", line 172, in insert
    kw["tags"] += (tag,)
TypeError: can only concatenate str (not "tuple") to str
```

However, I think that the way Python handles the declaration of tuples is the cause of the confusion here. `("hello")` is not a tuple, it is a string:
```python
>>> ("hello")
'hello'
```
whereas `("hello",)` *is* a tuple:
```python
>>> ("hello",)
('hello',)
```
This is so that string declarations can be made to easily span multiple lines in Python by wrapping them in parentheses.

Therefore, the argument to `tags` should always be wrapped in parentheses *and*, if it contains only a single element, the element *must* be followed by a comma.

If this is not what you are seeing, please let me know, because then it could be a proper bug that needs to be fixed. Of course, without seeing the whole code, I cannot determine with certainty that this is the cause of the confusion, but it is my best guess. I hope this helps you!

**Comment by WinEunuuchs2Unix** [comment]
Indeed I was sloppy and was not declaring a tuple by appending `,` after a single string tuple. Sorry for newbie question. Thank you for the great answer!
