### ISSUE TITLE
Graphics glitches in TickScale widget

### ISSUE THREAD

**Issue by ginop-1** [TkinterEP/ttkwidgets#73]
It all started from the fact that a normal `tk.Scale` was not themed correctly (I'm using a custom theme).
I then switched to `ttk.Scale` but it was not showing the value above the slider when I changed it.
I then discovered `ttkwidget`, which seems to work but with graphical glitches.

![screen](https://user-images.githubusercontent.com/69142763/108344632-ab43f200-71dd-11eb-9f0b-820b8f62be3d.png)
(The part in red should not appear)

Code: https://pastebin.com/bxgvsjSF
P.S. Furthermore, the the widgets that have problems are very slow to load widgets. 
Is this a problem that regards my code or the ttkwidget library?

**Comment by RedFantom** [comment]
The graphical glitch you're seeing is actually the widget working as intended.

You specify `tickinterval=1` for the left-most `TickScale`, causing it to create labels for all values from `1` to `30`. The same actually happens for the others, but due to the even higher number of labels, you don't see anything. There is no space for all those labels to be displayed correctly. Currently, they overlap, but they do so in a way that looks really weird. Try setting `tickinterval` to a larger value. It might take some experimentation to find a value that looks nice for you.

**Comment by ginop-1** [comment]
> u

Ok, thank you for explanation.
I need to remove this labels, but if i remove `tickinterval` it shows all the floating point value above the slider. 
Is there a way to have integers at top but not the label below?

**Comment by ginop-1** [comment]
SOLUTION: if you want only the value that "slides" and not the label at bottom, remove `tickinterval` and insert` digits=0` in the `TickScale` parameters
